# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

name: Anthony Platanios
email: e.a.platanios@cs.cmu.edu
description: > # this means to ignore newlines until "url:"
  My personal website.

url:  # the base hostname & protocol for your site
baseurl: /website  # the subpath of your site, e.g. /blog/

# Social
github_username: eaplatanios  # put your github username
# twitter_username: # put your twitter username
linkedin_username: eplatanios  # put your linkedin username
scholar_authorid: EFVk-mwAAAAJ  # put your google scholar author id
contact_note: Feel free to drop me a line via email.

# Footer text
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.

# Blog
# blog_name: al-folio
# blog_description: simple whitespace theme for academics

# Collections
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Pagination
# paginate: 15
# permalink: /blog/:year/:title/
# paginate_path: /blog/page:num/

# Includes
include: ['_pages']

# Gems
gems:
    # - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:
  last_name: Platanios
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other advanced settings (don't touch if you are not sure)
# -----------------------------------------------------------------------------
fontawesome_version: "4.6.3"
jquery_version: "1.12.4"
katex_version: "0.6.0"
